In [1]:
import os
from sklearn.model_selection import train_test_split
import numpy as np
from scipy.io import loadmat, savemat
import tensorflow as tf
from tensorflow.keras import models,Model
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from tensorflow.keras.layers import Input, Conv2D, AveragePooling2D, MaxPooling2D, Flatten, Dense,Dropout
from tensorflow.keras.optimizers import Adam,RMSprop
from  tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.datasets import mnist

In [2]:
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"


In [3]:
# def normal_signal(data):
#     mean, var = data.mean(axis=0), data.var(axis=0)
#     data_norm = (data - mean) / np.sqrt(var)
#     data_norm = data_norm.astype("float32")
#
#     return data_norm
#


In [4]:
data_x_ori = loadmat('classes7_huidu_6012.mat')['huidu']
print(data_x_ori.shape)
print(data_x_ori)

(1024, 3500)
[[0.34790204 0.29145404 0.46699019 ... 0.38575881 0.28163951 0.49064777]
 [0.32766406 0.30024244 0.44238864 ... 0.38508572 0.55258993 0.48241647]
 [0.31142259 0.26153049 0.34829383 ... 0.39679656 0.69595266 0.46294237]
 ...
 [0.34399618 0.29031028 0.59751737 ... 0.43515192 0.51712831 0.44959187]
 [0.27416032 0.25587033 0.40607887 ... 0.6873064  0.51315498 0.31350113]
 [0.2538729  0.34272782 0.51024724 ... 0.50116238 0.50645334 0.31006048]]


In [5]:
# data_x_normal = normal_signal(data_x_ori)
# print(data_x_normal)


In [6]:
data_x_swapaxes = data_x_ori.swapaxes(1,0)
print(data_x_swapaxes.shape)
print(data_x_swapaxes)

(3500, 1024)
[[0.34790204 0.32766406 0.31142259 ... 0.34399618 0.27416032 0.2538729 ]
 [0.29145404 0.30024244 0.26153049 ... 0.29031028 0.25587033 0.34272782]
 [0.46699019 0.44238864 0.34829383 ... 0.59751737 0.40607887 0.51024724]
 ...
 [0.38575881 0.38508572 0.39679656 ... 0.43515192 0.6873064  0.50116238]
 [0.28163951 0.55258993 0.69595266 ... 0.51712831 0.51315498 0.50645334]
 [0.49064777 0.48241647 0.46294237 ... 0.44959187 0.31350113 0.31006048]]


In [7]:
data_x = data_x_swapaxes.reshape((-1,32,32))
print(data_x.shape)
print(data_x)

(3500, 32, 32)
[[[0.34790204 0.32766406 0.31142259 ... 0.33892844 0.36776097 0.33386071]
  [0.27547876 0.30233363 0.28919872 ... 0.3329378  0.2822687  0.42954613]
  [0.30588516 0.35933946 0.27323742 ... 0.53490557 0.17161904 0.45254458]
  ...
  [0.11403639 0.89295956 0.04949899 ... 0.52612149 0.11256139 0.45489304]
  [0.1183625  0.49521243 0.18613006 ... 0.42138831 0.40763539 0.32212664]
  [0.2598553  0.32157454 0.36999407 ... 0.34399618 0.27416032 0.2538729 ]]

 [[0.29145404 0.30024244 0.26153049 ... 0.34482961 0.42503959 0.50041058]
  [0.44071989 0.37549612 0.33227755 ... 0.56616224 0.28096467 0.54476313]
  [0.13810194 0.47139617 0.22695368 ... 0.94700569 0.16116292 0.66199386]
  ...
  [0.21090191 0.66968737 0.16853383 ... 0.35572956 0.33130975 0.42917473]
  [0.3351614  0.34272782 0.34625687 ... 0.43281131 0.3374978  0.24805951]
  [0.28192269 0.43906778 0.51956126 ... 0.29031028 0.25587033 0.34272782]]

 [[0.46699019 0.44238864 0.34829383 ... 0.60861259 0.38132407 0.5706273 ]
  [0.33

In [8]:
# print(data_x[0,:,:])

In [9]:
# data_x_normal = data_x / 255
# print(data_x_normal)
# print(data_x_normal[0,:,:])


In [10]:
data_x_dims = np.expand_dims(data_x, axis=-1)
print(data_x_dims.shape)
print(data_x_dims)

(3500, 32, 32, 1)
[[[[0.34790204]
   [0.32766406]
   [0.31142259]
   ...
   [0.33892844]
   [0.36776097]
   [0.33386071]]

  [[0.27547876]
   [0.30233363]
   [0.28919872]
   ...
   [0.3329378 ]
   [0.2822687 ]
   [0.42954613]]

  [[0.30588516]
   [0.35933946]
   [0.27323742]
   ...
   [0.53490557]
   [0.17161904]
   [0.45254458]]

  ...

  [[0.11403639]
   [0.89295956]
   [0.04949899]
   ...
   [0.52612149]
   [0.11256139]
   [0.45489304]]

  [[0.1183625 ]
   [0.49521243]
   [0.18613006]
   ...
   [0.42138831]
   [0.40763539]
   [0.32212664]]

  [[0.2598553 ]
   [0.32157454]
   [0.36999407]
   ...
   [0.34399618]
   [0.27416032]
   [0.2538729 ]]]


 [[[0.29145404]
   [0.30024244]
   [0.26153049]
   ...
   [0.34482961]
   [0.42503959]
   [0.50041058]]

  [[0.44071989]
   [0.37549612]
   [0.33227755]
   ...
   [0.56616224]
   [0.28096467]
   [0.54476313]]

  [[0.13810194]
   [0.47139617]
   [0.22695368]
   ...
   [0.94700569]
   [0.16116292]
   [0.66199386]]

  ...

  [[0.21090191]
   [0

In [11]:
# data_x_normal = tf.cast(data_x, dtype = tf.float32) / 255
# print(data_x_normal)
# print(data_x_normal[0,:,:])

In [12]:
# data_x_dims = tf.expand_dims(data_x_normal, axis=-1)
#

In [13]:
data_y_ori = loadmat('classes7_huidu_6012.mat')['real_label']
print(data_y_ori.shape)
print(data_y_ori)

(1, 3500)
[[0 0 0 ... 6 6 6]]


In [14]:
data_y_dims = np.squeeze(data_y_ori, axis=0)
print(data_y_dims.shape)
print(data_y_dims)
# data_y_dims = np.expand_dims(data_y_dims, axis=-1)
# print(data_y_dims)

(3500,)
[0 0 0 ... 6 6 6]


In [15]:
data_y_onehot = np.eye(7)[data_y_dims]
print(data_y_onehot.shape)
print(data_y_onehot)

(3500, 7)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [16]:
# data_y = tf.cast(data_y_ori, dtype=tf.float32)
# print(data_y)

In [17]:
# data_y_dims = tf.squeeze(data_y, axis=0)
# print(data_y_dims)
# data_y_dims = tf.expand_dims(data_y_dims, axis=-1)
# print(data_y_dims)

In [18]:
train_x, test_x, train_y, test_y = train_test_split(data_x_dims, data_y_onehot, test_size=0.2)
print(train_x.shape, train_x)
print(train_y.shape, train_y)
print(test_x.shape, test_x)
print(test_y.shape, test_y)

(2800, 32, 32, 1) [[[[0.37785517]
   [0.33603956]
   [0.34957698]
   ...
   [0.37893182]
   [0.37896295]
   [0.37869506]]

  [[0.36207974]
   [0.3710137 ]
   [0.36358647]
   ...
   [0.38789691]
   [0.39606773]
   [0.39341411]]

  [[0.37901147]
   [0.36988347]
   [0.36704739]
   ...
   [0.38798886]
   [0.38644665]
   [0.3848219 ]]

  ...

  [[0.37660837]
   [0.36571443]
   [0.36575715]
   ...
   [0.36463488]
   [0.36002273]
   [0.35685071]]

  [[0.35659874]
   [0.36905444]
   [0.35987937]
   ...
   [0.35929942]
   [0.36545884]
   [0.39056356]]

  [[0.37901291]
   [0.37429867]
   [0.3737513 ]
   ...
   [0.37020132]
   [0.36054839]
   [0.38024596]]]


 [[[0.37319793]
   [0.374117  ]
   [0.36797867]
   ...
   [0.36582492]
   [0.37075049]
   [0.37463718]]

  [[0.36697047]
   [0.36275137]
   [0.36508995]
   ...
   [0.37460649]
   [0.37763913]
   [0.36778945]]

  [[0.36248251]
   [0.35950467]
   [0.36269584]
   ...
   [0.36953992]
   [0.37604281]
   [0.37673759]]

  ...

  [[0.38947161]
   [0

In [19]:
# dataset = tf.data.Dataset.from_tensor_slices((data_x_dims, data_y_dims)).shuffle(data_x.shape[0]).batch(16)

In [20]:
# def cnn():
#     inputs = Input(shape=(32, 32, 1))
#     cnn1 = Conv2D(filters=64, kernel_size=(5, 5), strides=(1, 1), padding='valid', activation='tanh')(inputs)  # 6, 24*24
#     max1 = MaxPooling2D(pool_size=(2, 2))(cnn1)  # 6, 12*12
#     cnn2 = Conv2D(filters=32, kernel_size=(3, 3), strides=(1, 1), padding='valid', activation='tanh')(max1)  # 12, 8*8
#     max2 = MaxPooling2D(pool_size=(2, 2))(cnn2)  # 12, 4*4
#
#     outputs = Dense(units=6, activation='softmax')(max2)  # 10
#
#     model = Model(inputs, outputs)
#     return model

In [21]:
# model = cnn()
# model.summary()
# model.compile(optimizer=Adam(learning_rate=0.1), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
#

In [22]:
# history = model.fit(train_x, train_y, epochs=100, batch_size=64, shuffle='True', validation_data=(test_x, test_y))

In [23]:
model = models.Sequential()
model.add(layers.Conv2D(4,(10,10),padding='same',activation='relu',input_shape=(32,32,1)))
model.add(layers.MaxPooling2D((3,3),strides=2))
model.add(layers.Conv2D(4,(5,5),padding='same',activation='relu'))
model.add(layers.MaxPooling2D((3,3),strides=2))
model.add(layers.Conv2D(8,(3,3),padding='same',activation='relu'))
model.add(layers.Conv2D(8,(3,3),padding='same',activation='relu'))
model.add(layers.Conv2D(8,(3,3),padding='same',activation='relu'))
model.add(layers.MaxPooling2D((3,3),strides=2))
model.add(layers.Flatten())
model.add(layers.Dense(64,activation='relu'))
model.add((layers.Dense(7,activation='softmax')))






In [24]:
model.compile(optimizer=RMSprop(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])



In [25]:
model.summary()

save = ModelCheckpoint(
                                filepath='./model/classes7_huidu_6012.h5',
                                monitor='val_accuracy',
                                save_best_only=True,

                                mode='max',
                        )

lr = ReduceLROnPlateau(monitor='val_accuracy',
                       factor=0.5,
                       patience=30,
                       min_delta=0.0001,
                       min_lr=0

                        )

callback_list = [save,lr]




history = model.fit(train_x,train_y,epochs=150, batch_size=16,validation_data=(test_x, test_y),callbacks=callback_list)
#绘制训练过程中的损失曲线和精度曲线



#---------------------------histpry-----------------------------
history.history
savemat('./model/classes7_huidu_6012_loss.mat', dict(
    loss=history.history['loss'], acc=history.history['accuracy'],
    val_loss=history.history['val_loss'], val_acc=history.history['val_accuracy']
                                                )
        )



Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 32, 4)         404       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 4)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 15, 15, 4)         404       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 4)           0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 7, 7, 8)           296       
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 7, 7, 8)           584       
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 7, 7, 8)           5

In [26]:
#----------------------测试---------------------------

In [28]:
new_model1 = models.load_model('E:/learn/code/dx6/model/classes7_huidu_6012.h5')
# new_model1.summary()

In [29]:
print(new_model1.evaluate(test_x, test_y))

22/22 [==============================] - 0s 3ms/step - loss: 0.0204 - accuracy: 0.9986
[0.020425040274858475, 0.9985714554786682]


In [35]:
output = new_model1.predict(data_x_dims)
output


array([[1.0000000e+00, 3.1594100e-33, 0.0000000e+00, ..., 0.0000000e+00,
        6.6772390e-30, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        6.4822580e-36, 0.0000000e+00],
       [1.0000000e+00, 1.7831186e-33, 0.0000000e+00, ..., 0.0000000e+00,
        1.4574438e-34, 0.0000000e+00],
       ...,
       [0.0000000e+00, 0.0000000e+00, 1.3362465e-13, ..., 2.8151344e-25,
        5.9990692e-20, 1.0000000e+00],
       [7.7525271e-22, 2.7787651e-29, 7.5189240e-07, ..., 6.9350145e-16,
        6.1625683e-12, 9.9999917e-01],
       [0.0000000e+00, 0.0000000e+00, 2.2441121e-18, ..., 1.0063448e-30,
        6.0954396e-30, 1.0000000e+00]], dtype=float32)

In [36]:
savemat('./model/classes7_huidu_6012_allDataOutput.mat', dict(outputs=output))


In [30]:
# import matplotlib.pyplot as plt
#
# acc = history.history['accuracy']
# loss = history.history['loss']
# epochs = range(1,len(acc) + 1)
# plt.plot(epochs,acc,'bo',label='Training acc')
# plt.title('Training  accuracy')
# plt.legend()
# plt.figure()
# plt.plot(epochs,loss,'bo',label='Training loss')
# plt.title('Training  loss')
# plt.legend()
# plt.show()
#
# print(history.history.keys())
# print(model.evaluate(test_x, test_y))

In [31]:
# ----------------------------最佳模型的参数导出-------------------------------

In [32]:
# model.save('model_v3_lr=0.0001_epoch1.h5', save_traces=False)
new_model2 = models.load_model('E:/learn/code/dx6/model/classes7_huidu_6012.h5')
# new_model2.summary()
# print(outputs_test.shape)
# print(outputs_test)
# savemat('outputs_tset_v3_lr=0.0001_epoch1.mat', dict(outputs=outputs_test))


In [33]:
weights = np.array(new_model2.get_weights(), dtype=object)
# print(weights.shape)
# # (4,)权重由4部分组成
# # print(weights[0].shape)
# # (784, 64)dense_1 w1
# # print(weights[1].shape)
# # (64,)dense_1 b1
# # print(weights[2].shape)
# # (64, 10)dense_2 w2
# # print(weights[3].shape)
# # (10,)dense_2 b2
# # print(weights[4].shape)
# # print(weights[5].shape)
savemat('./model/classes7_huidu_6012_weight.mat', dict(weights=weights))
# # np.save('weights.npy', weights)

[[[ 0.27858657 -0.11032599  0.24256352  0.36759272]
  [ 0.08975185 -0.10723591 -0.02123244  0.00288844]
  [ 0.05501748 -0.04072938  0.2315243   0.1318572 ]
  [ 0.20920897  0.18813749  0.12406431  0.25484413]
  [ 0.25686973  0.05315118 -0.08031166  0.24063075]]

 [[ 0.19313557 -0.08968989  0.1354165   0.21789181]
  [ 0.23441102 -0.02861835  0.07250351  0.11338403]
  [-0.02714243  0.13866045  0.22989765  0.234159  ]
  [ 0.25558934  0.09735649  0.00288611  0.3179827 ]
  [-0.01781337  0.22774687  0.21401136  0.3348234 ]]

 [[ 0.11895558  0.07083923 -0.0089698   0.3306979 ]
  [ 0.21509655  0.22910346 -0.1304356   0.22664465]
  [ 0.14243919 -0.05880789 -0.0623595   0.12688187]
  [ 0.13814406  0.05518676  0.05876957  0.3520218 ]
  [ 0.32759848 -0.00542256  0.07507815  0.03140919]]

 [[ 0.21444057  0.02549149  0.18373482  0.00173025]
  [ 0.22021447  0.10022712  0.07573871  0.08809531]
  [ 0.11397597  0.23758484 -0.15114763 -0.01247049]
  [ 0.02482653  0.10542525  0.12698376  0.12001035]
  [ 0.

In [29]:

# ----------------------------------2.获取每一层输出------------------------

(1800, 32, 32, 1)
[[[[ 5.19487179e-01]
   [ 6.79487179e-01]
   [ 8.84615385e-01]
   ...
   [ 2.62051282e-01]
   [ 3.20000000e-01]
   [ 3.66666667e-01]]

  [[ 3.13333333e-01]
   [ 2.17948718e-01]
   [ 2.23076923e-01]
   ...
   [ 6.75384615e-01]
   [ 5.11794872e-01]
   [ 3.51282051e-01]]

  [[ 3.63589744e-01]
   [ 4.02051282e-01]
   [ 3.97435897e-01]
   ...
   [ 3.02051282e-01]
   [ 4.71794872e-01]
   [ 4.93846154e-01]]

  ...

  [[ 4.76410256e-01]
   [ 4.38974359e-01]
   [ 4.48205128e-01]
   ...
   [ 5.68717949e-01]
   [ 4.22564103e-01]
   [ 2.70256410e-01]]

  [[ 3.15384615e-01]
   [ 4.18461538e-01]
   [ 4.88205128e-01]
   ...
   [ 5.20000000e-01]
   [ 6.34358974e-01]
   [ 6.24102564e-01]]

  [[ 4.71282051e-01]
   [ 3.73846154e-01]
   [ 4.23076923e-01]
   ...
   [ 3.68205128e-01]
   [ 3.11282051e-01]
   [ 2.44102564e-01]]]


 [[[ 3.78680927e-04]
   [-7.41247772e-04]
   [-1.24642424e-03]
   ...
   [-1.53083779e-04]
   [-4.79393939e-04]
   [ 2.45739750e-04]]

  [[ 1.26334403e-03]
   [ 1.